#!/usr/bin/env node
/**
 * Generate an explicit sidebars.js from ../docs.
 * Useful if you want full control instead of {type:'autogenerated'}.
 *
 * Usage: npm run gen-sidebar
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DOCS = path.resolve(__dirname, '../../docs');
const OUT = path.resolve(__dirname, '../sidebars.generated.js');

function walk(dir, base = '') {
  const items = [];
  for (const name of fs.readdirSync(dir).sort()) {
    const full = path.join(dir, name);
    const rel = path.join(base, name);
    const stat = fs.statSync(full);
    if (stat.isDirectory()) {
      items.push({
        type: 'category',
        label: name.replace(/[-_]/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
        collapsible: true,
        collapsed: true,
        items: walk(full, rel),
      });
    } else if (/\.mdx?$/.test(name)) {
      const id = rel.replace(/\.mdx?$/, '').split(path.sep).join('/');
      items.push(id);
    }
  }
  return items;
}

if (!fs.existsSync(DOCS)) {
  console.error(`docs folder not found at ${DOCS}`);
  process.exit(1);
}

const sidebar = { docs: walk(DOCS) };
fs.writeFileSync(
  OUT,
  `/** Auto-generated. Do not edit. */\nmodule.exports = ${JSON.stringify(sidebar, null, 2)};\n`
);
console.log(`Wrote ${OUT}`);
