/**
 * Auto-generated sidebar from the `../docs` folder hierarchy.
 *
 * Docusaurus's built-in `{type: 'autogenerated'}` walks the docs directory
 * and creates a nested, collapsible sidebar that mirrors the folder tree —
 * exactly the Crossplane-style UX requested.
 *
 * To customize order, add `_category_.json` files in subfolders, e.g.:
 *   { "label": "Concepts", "position": 2, "collapsed": false }
 *
 * Or add `sidebar_position: 1` frontmatter to individual .md files.
 *
 * To regenerate an explicit sidebar from disk, run: `npm run gen-sidebar`.
 */
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
